server:
  port: 1314
spring:
  datasource:
    url: jdbc:mysql://182.61.58.90:3306/nats?useSSL=false&allowMultiQueries=true
    username: root
    password: Xia5201314@
  profiles:
    include: fdfs

mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: org.danmo.domain.entity